// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGJDHHKVTLFKHailydK9dOIEi6kG-M2so',
    appId: '1:730798082266:web:716f2a680907a9bf6dbde3',
    messagingSenderId: '730798082266',
    projectId: 'login-app-d65e5',
    authDomain: 'login-app-d65e5.firebaseapp.com',
    storageBucket: 'login-app-d65e5.firebasestorage.app',
    measurementId: 'G-VNJFXCMXSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsoicuGnoaEoLtlwajlMOcreltU_uJbX0',
    appId: '1:730798082266:android:c16406745fe4690a6dbde3',
    messagingSenderId: '730798082266',
    projectId: 'login-app-d65e5',
    storageBucket: 'login-app-d65e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6hLEzYbg-NuEBXqiOZxG8CQoFgiOj28E',
    appId: '1:730798082266:ios:f2d1758fe7b56b9f6dbde3',
    messagingSenderId: '730798082266',
    projectId: 'login-app-d65e5',
    storageBucket: 'login-app-d65e5.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6hLEzYbg-NuEBXqiOZxG8CQoFgiOj28E',
    appId: '1:730798082266:ios:f2d1758fe7b56b9f6dbde3',
    messagingSenderId: '730798082266',
    projectId: 'login-app-d65e5',
    storageBucket: 'login-app-d65e5.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGJDHHKVTLFKHailydK9dOIEi6kG-M2so',
    appId: '1:730798082266:web:257d82916346d1cb6dbde3',
    messagingSenderId: '730798082266',
    projectId: 'login-app-d65e5',
    authDomain: 'login-app-d65e5.firebaseapp.com',
    storageBucket: 'login-app-d65e5.firebasestorage.app',
    measurementId: 'G-VG5ZL96YZR',
  );
}
